Add DOM lib to resolve types error
Due to the way we use yarn types are visible to all packages.

This resolves:

  ../../node_modules/@types/recharts/index.d.ts(151,78): error TS2304:
  Cannot find name 'CSSStyleDeclaration'.